# Generated by Django 5.1.4 on 2025-01-07 12:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnails')),
                ('categories', models.JSONField(blank=True, default=list, null=True)),
                ('favourite', models.BooleanField(default=False)),
                ('group', models.CharField(choices=[('top10', 'Top 10'), ('scifi', 'Sci-Fi'), ('award-winning', 'Award-Winning'), ('us-series', 'US Series'), ('comedy', 'Comedy'), ('action', 'Action'), ('fantasy', 'Fantasy'), ('romance', 'Romance'), ('mystery', 'Mystery'), ('crime', 'Crime'), ('horror', 'Horror'), ('drama', 'Drama'), ('family', 'Family'), ('thriller', 'Thriller')], default='top10', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Video120p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file_120p', models.FileField(blank=True, null=True, upload_to='videos')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_120p', to='videos_app.video')),
            ],
        ),
        migrations.CreateModel(
            name='Video720p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file_720p', models.FileField(blank=True, null=True, upload_to='videos')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_720p', to='videos_app.video')),
            ],
        ),
    ]
