# Generated by Django 5.1.4 on 2025-01-07 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_file', models.FileField(blank=True, null=True, upload_to='thumbnails')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_instance', to='videos_app.video')),
            ],
        ),
    ]
