# Generated by Django 5.1.4 on 2025-01-08 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0002_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video360p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file_360p', models.FileField(blank=True, null=True, upload_to='videos')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_360p', to='videos_app.video')),
            ],
        ),
    ]
