# Generated by Django 5.1.4 on 2025-01-17 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0005_alter_thumbnail_thumbnail_file_alter_video_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video480p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file_480p', models.FileField(blank=True, null=True, upload_to='')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_480p', to='videos_app.video')),
            ],
        ),
        migrations.DeleteModel(
            name='Video120p',
        ),
    ]
