# Generated by Django 5.1.4 on 2025-01-17 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0006_video480p_delete_video120p'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video1080p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file_1080p', models.FileField(blank=True, null=True, upload_to='')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_1080p', to='videos_app.video')),
            ],
        ),
    ]
