# Generated by Django 5.0.6 on 2024-07-15 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_video_file_480p'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video480p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file_480p', models.FileField(blank=True, null=True, upload_to='videos/480p')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_480p', to='videos.video')),
            ],
        ),
    ]
