# Generated by Django 5.0.6 on 2024-07-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video480p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file_480p',
        ),
        migrations.AlterField(
            model_name='video480p',
            name='video_file_480p',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
