# Generated by Django 5.0.6 on 2024-07-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='video',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
