# Generated by Django 5.0.6 on 2024-07-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_video_categories_video_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='group',
            field=models.CharField(choices=[('top10', 'Top 10'), ('scifi', 'Sci Fi'), ('preisgekrönt', 'Preisgekrönt'), ('us-serien', 'US-Serien'), ('comedy', 'Comedy'), ('action', 'Action')], default='top10', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='categories',
            field=models.JSONField(default=list),
        ),
    ]
