# Generated by Django 5.0.6 on 2024-08-07 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_video_group_alter_video_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video720p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file_720p', models.FileField(blank=True, null=True, upload_to='videos')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_720p', to='videos.video')),
            ],
        ),
    ]
