# Generated by Django 5.0.6 on 2024-08-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_video720p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='categories',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
